- name: download war
  local_action: get_url url={{ downloadUrl }}/{{ warName }} dest=/etc/ansible/roles/webServers1/files/ force=yes
  register: Isdownloaded
- name: task will exit if download war failed
  fail: msg="download war failed,the task stop!!!"
  when: "'OK' not in Isdownloaded.msg"
- name: shutdown tomcat  
  shell: chdir={{ tomcatHome }}/bin ./shutdown.sh
- name: waiting for tomcat stop...
  wait_for: host={{ inventory_hostname }} port={{ serverPort }} delay=3 state=stopped timeout=10
  register: Isdown
- name: tomcat pid
  shell: "ps -ef | grep -v grep | grep -w {{ tomcatHome }} | awk '{print $2}'" 
  when: "'state' in Isdown and Isdown.state != 'stopped'"
  register: processId
- name: force kill tomcat
  command: "kill -9 {{ processId.stdout_lines }}"
  when: "'state' in Isdown and Isdown.state != 'stopped'"
- name: pause 3s
  pause: seconds=3
- name: backup old war
  command: "mv -f {{ warRemotePath }}/{{ warName }} {{ warRemotePath }}/{{ warName }}.bak"
  ignore_errors: True
- name: del old war dir
  file: path={{ warRemotePath }}/{{ warDir }} state=absent force=yes
- name: copy war to server  
  copy: src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }} 
- name: start tomcat
  shell: chdir={{ tomcatHome }}/bin nohup ./startup.sh &
- name: waiting for tomcat startup...
  wait_for: host={{ inventory_hostname }} port={{ serverPort }} delay=30
- name: tomcat startup finished!
  command: echo "start SUCCESSFULL!!!"
